---
- name: Install deps for apt module
  shell: apt-get update && apt-get install -y python-apt aptitude
  become: true

- name: Update system
  apt:
    upgrade: yes
    update_cache: yes
  become: true

- name: Reboot system if required
  shell: sleep 2 && /sbin/shutdown -r now 'Rebooting to complete system upgrade'
  args:
    removes: /var/run/reboot-required
  become: yes
  async: 1
  poll: 0
  ignore_errors: true
  register: reboot

- name: Wait for system to return from reboot
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    state: started
    port: 22
    delay: 1
    timeout: 300

- name: Install some basic packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - vim
    - python-pip
  become: true

- name: Install some basic pypi packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - git-review
    - pbr
    - tox
    - virtualenv
  become: true

# TODO(jroll) make version a variable
- name: Clone devstack
  git:
    repo: git://git.openstack.org/openstack-dev/devstack.git
    dest: /opt/stack/devstack
    version: master

- name: Copy up git configs
  copy:
    src: "{{ lookup('env', 'HOME') + '/.gitconfig' }}"
    dest: /opt/stack/.gitconfig
    owner: stack
    group: stack
